import { db } from "@/lib/db"
import { items, entities } from "@/lib/db/schema"
import { sql } from "drizzle-orm"

const allItems = [
  // Weapons
  {
    slug: "plasma-cannon-i",
    name: "Plasma Cannon I",
    type: "weapon" as const,
    rarity: "common" as const,
    creditCost: 80,
    icon: "🔫",
    bonusAtk: 5,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A basic plasma cannon. Reliable and effective for new pilots.",
  },
  {
    slug: "ion-blaster-ii",
    name: "Ion Blaster II",
    type: "weapon" as const,
    rarity: "uncommon" as const,
    creditCost: 200,
    icon: "⚡",
    bonusAtk: 10,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "An ion-charged blaster that disrupts enemy shields.",
  },
  {
    slug: "pulse-rifle-ii",
    name: "Pulse Rifle II",
    type: "weapon" as const,
    rarity: "uncommon" as const,
    creditCost: 250,
    icon: "🎯",
    bonusAtk: 12,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A rapid-fire pulse rifle with increased attack power.",
  },
  {
    slug: "void-lance-iii",
    name: "Void Lance III",
    type: "weapon" as const,
    rarity: "rare" as const,
    creditCost: 450,
    icon: "🗡️",
    bonusAtk: 15,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A lance forged from void matter. Pierces through enemy defenses.",
  },
  {
    slug: "nova-cannon-iv",
    name: "Nova Cannon IV",
    type: "weapon" as const,
    rarity: "epic" as const,
    creditCost: 900,
    icon: "💥",
    bonusAtk: 25,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A devastating nova cannon that unleashes supercharged energy blasts.",
  },
  {
    slug: "singularity-beam-v",
    name: "Singularity Beam V",
    type: "weapon" as const,
    rarity: "legendary" as const,
    creditCost: 2000,
    icon: "🌟",
    bonusAtk: 38,
    bonusDef: 0,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A legendary weapon that harnesses the power of a singularity. Unmatched destructive force.",
  },
  // Shields
  {
    slug: "hull-plating-i",
    name: "Hull Plating I",
    type: "shield" as const,
    rarity: "common" as const,
    creditCost: 80,
    icon: "🛡️",
    bonusAtk: 0,
    bonusDef: 5,
    bonusSpd: 0,
    bonusHp: 0,
    description: "Basic reinforced hull plating. Provides modest protection.",
  },
  {
    slug: "deflector-shield-ii",
    name: "Deflector Shield II",
    type: "shield" as const,
    rarity: "uncommon" as const,
    creditCost: 200,
    icon: "🔵",
    bonusAtk: 0,
    bonusDef: 10,
    bonusSpd: 0,
    bonusHp: 0,
    description: "An energy deflector that redirects incoming fire.",
  },
  {
    slug: "resonance-shield-ii",
    name: "Resonance Shield II",
    type: "shield" as const,
    rarity: "uncommon" as const,
    creditCost: 250,
    icon: "🔷",
    bonusAtk: 0,
    bonusDef: 12,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A resonance-tuned shield that absorbs and disperses impact energy.",
  },
  {
    slug: "phase-barrier-iii",
    name: "Phase Barrier III",
    type: "shield" as const,
    rarity: "rare" as const,
    creditCost: 450,
    icon: "💠",
    bonusAtk: 0,
    bonusDef: 16,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A phase-shifted barrier that exists partially out of normal space.",
  },
  {
    slug: "aegis-field-iv",
    name: "Aegis Field IV",
    type: "shield" as const,
    rarity: "epic" as const,
    creditCost: 900,
    icon: "🌐",
    bonusAtk: 0,
    bonusDef: 24,
    bonusSpd: 0,
    bonusHp: 0,
    description: "An advanced aegis field generator. Near-impenetrable defensive matrix.",
  },
  {
    slug: "stellar-fortress-v",
    name: "Stellar Fortress V",
    type: "shield" as const,
    rarity: "legendary" as const,
    creditCost: 2000,
    icon: "⭐",
    bonusAtk: 0,
    bonusDef: 35,
    bonusSpd: 0,
    bonusHp: 0,
    description: "A legendary fortress-class shield array. Forged from collapsed star material.",
  },
  // Engines
  {
    slug: "ion-drive-i",
    name: "Ion Drive I",
    type: "engine" as const,
    rarity: "common" as const,
    creditCost: 80,
    icon: "🚀",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 5,
    bonusHp: 0,
    description: "A standard ion drive. Improves maneuverability in combat.",
  },
  {
    slug: "warp-cell-ii",
    name: "Warp Cell II",
    type: "engine" as const,
    rarity: "uncommon" as const,
    creditCost: 200,
    icon: "🌀",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 10,
    bonusHp: 0,
    description: "A warp-capable cell that boosts combat speed significantly.",
  },
  {
    slug: "burst-drive-ii",
    name: "Burst Drive II",
    type: "engine" as const,
    rarity: "uncommon" as const,
    creditCost: 250,
    icon: "💨",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 12,
    bonusHp: 0,
    description: "A burst-mode drive that delivers short bursts of extreme acceleration.",
  },
  {
    slug: "hyperdrive-iii",
    name: "Hyperdrive III",
    type: "engine" as const,
    rarity: "rare" as const,
    creditCost: 450,
    icon: "✨",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 14,
    bonusHp: 0,
    description: "A military-grade hyperdrive core. Enables rapid repositioning mid-battle.",
  },
  {
    slug: "quantum-thruster-iv",
    name: "Quantum Thruster IV",
    type: "engine" as const,
    rarity: "epic" as const,
    creditCost: 900,
    icon: "⚛️",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 22,
    bonusHp: 0,
    description: "Quantum-entangled thrusters that allow near-instantaneous movement.",
  },
  {
    slug: "void-runner-v",
    name: "Void Runner V",
    type: "engine" as const,
    rarity: "legendary" as const,
    creditCost: 2000,
    icon: "🌌",
    bonusAtk: 0,
    bonusDef: 0,
    bonusSpd: 32,
    bonusHp: 0,
    description: "A legendary engine system that phases through the void itself. Unparalleled speed.",
  },
]

const allEntities = [
  // Common
  {
    slug: "rogue-drone",
    name: "Rogue Drone",
    rarity: "common" as const,
    hp: 80,
    atk: 8,
    def: 6,
    spd: 8,
    creditReward: 15,
    xpReward: 10,
    icon: "🤖",
    lootTable: [
      { itemSlug: "hull-plating-i", chance: 0.1 },
      { itemSlug: "ion-drive-i", chance: 0.1 },
    ],
    requiresFleet: false,
    description: "A malfunctioning mining drone gone rogue. Attacks anything in range.",
  },
  {
    slug: "corrupted-probe",
    name: "Corrupted Probe",
    rarity: "common" as const,
    hp: 90,
    atk: 10,
    def: 5,
    spd: 10,
    creditReward: 18,
    xpReward: 12,
    icon: "🔴",
    lootTable: [
      { itemSlug: "plasma-cannon-i", chance: 0.1 },
      { itemSlug: "hull-plating-i", chance: 0.08 },
    ],
    requiresFleet: false,
    description: "A corrupted deep-space probe infected with hostile code. Fast and aggressive.",
  },
  // Uncommon
  {
    slug: "void-stalker",
    name: "Void Stalker",
    rarity: "uncommon" as const,
    hp: 160,
    atk: 16,
    def: 12,
    spd: 14,
    creditReward: 35,
    xpReward: 25,
    icon: "👻",
    lootTable: [
      { itemSlug: "ion-blaster-ii", chance: 0.12 },
      { itemSlug: "deflector-shield-ii", chance: 0.10 },
    ],
    requiresFleet: false,
    description: "A predatory entity that lurks in the void between stars. Difficult to detect until it strikes.",
  },
  {
    slug: "plasma-wraith",
    name: "Plasma Wraith",
    rarity: "uncommon" as const,
    hp: 170,
    atk: 20,
    def: 10,
    spd: 18,
    creditReward: 40,
    xpReward: 28,
    icon: "💜",
    lootTable: [
      { itemSlug: "pulse-rifle-ii", chance: 0.12 },
      { itemSlug: "warp-cell-ii", chance: 0.10 },
    ],
    requiresFleet: false,
    description: "A sentient plasma entity that attacks with superheated bursts. Extremely fast.",
  },
  {
    slug: "nebula-shade",
    name: "Nebula Shade",
    rarity: "uncommon" as const,
    hp: 180,
    atk: 18,
    def: 14,
    spd: 12,
    creditReward: 38,
    xpReward: 26,
    icon: "🌌",
    lootTable: [
      { itemSlug: "resonance-shield-ii", chance: 0.12 },
      { itemSlug: "burst-drive-ii", chance: 0.10 },
    ],
    requiresFleet: false,
    description: "A shadow creature born from nebula gases. Balances strong defense with steady attacks.",
  },
  // Rare
  {
    slug: "quantum-specter",
    name: "Quantum Specter",
    rarity: "rare" as const,
    hp: 300,
    atk: 28,
    def: 20,
    spd: 22,
    creditReward: 75,
    xpReward: 50,
    icon: "⚡",
    lootTable: [
      { itemSlug: "void-lance-iii", chance: 0.08 },
      { itemSlug: "phase-barrier-iii", chance: 0.08 },
    ],
    requiresFleet: false,
    description: "A quantum-displaced entity that attacks from multiple dimensions simultaneously.",
  },
  {
    slug: "dark-matter-fiend",
    name: "Dark Matter Fiend",
    rarity: "rare" as const,
    hp: 330,
    atk: 32,
    def: 18,
    spd: 25,
    creditReward: 80,
    xpReward: 55,
    icon: "🌑",
    lootTable: [
      { itemSlug: "hyperdrive-iii", chance: 0.08 },
      { itemSlug: "void-lance-iii", chance: 0.07 },
    ],
    requiresFleet: false,
    description: "A creature composed entirely of dark matter. Hits hard and moves with terrifying speed.",
  },
  {
    slug: "entropy-hound",
    name: "Entropy Hound",
    rarity: "rare" as const,
    hp: 350,
    atk: 30,
    def: 24,
    spd: 18,
    creditReward: 85,
    xpReward: 58,
    icon: "🐺",
    lootTable: [
      { itemSlug: "phase-barrier-iii", chance: 0.08 },
      { itemSlug: "hyperdrive-iii", chance: 0.07 },
    ],
    requiresFleet: false,
    description: "A hound-like entity that feeds on entropy. Heavily armored with relentless aggression.",
  },
  // Bosses
  {
    slug: "warlord-xarath",
    name: "Galactic Warlord Xarath",
    rarity: "boss" as const,
    hp: 1000,
    atk: 55,
    def: 45,
    spd: 30,
    creditReward: 300,
    xpReward: 200,
    icon: "👑",
    lootTable: [
      { itemSlug: "nova-cannon-iv", chance: 0.15 },
      { itemSlug: "aegis-field-iv", chance: 0.15 },
      { itemSlug: "quantum-thruster-iv", chance: 0.12 },
    ],
    requiresFleet: true,
    description: "The tyrannical warlord who commands the outer rim fleets. Only the most coordinated fleet can hope to defeat him.",
  },
  {
    slug: "void-titan",
    name: "The Void Titan",
    rarity: "boss" as const,
    hp: 1200,
    atk: 70,
    def: 60,
    spd: 20,
    creditReward: 500,
    xpReward: 350,
    icon: "🌀",
    lootTable: [
      { itemSlug: "singularity-beam-v", chance: 0.12 },
      { itemSlug: "stellar-fortress-v", chance: 0.12 },
      { itemSlug: "void-runner-v", chance: 0.12 },
    ],
    requiresFleet: true,
    description: "An ancient titan awakened from the void. Its power rivals that of a small star. Only a united fleet stands a chance.",
  },
]

async function main() {
  console.log("Seeding combat items...")
  await db
    .insert(items)
    .values(allItems)
    .onConflictDoUpdate({
      target: items.slug,
      set: {
        name: sql`excluded.name`,
        type: sql`excluded.type`,
        rarity: sql`excluded.rarity`,
        creditCost: sql`excluded.credit_cost`,
        icon: sql`excluded.icon`,
        bonusAtk: sql`excluded.bonus_atk`,
        bonusDef: sql`excluded.bonus_def`,
        bonusSpd: sql`excluded.bonus_spd`,
        bonusHp: sql`excluded.bonus_hp`,
        description: sql`excluded.description`,
      },
    })
  console.log(`  Inserted/updated ${allItems.length} items`)

  console.log("Seeding combat entities...")
  await db
    .insert(entities)
    .values(allEntities)
    .onConflictDoUpdate({
      target: entities.slug,
      set: {
        name: sql`excluded.name`,
        rarity: sql`excluded.rarity`,
        hp: sql`excluded.hp`,
        atk: sql`excluded.atk`,
        def: sql`excluded.def`,
        spd: sql`excluded.spd`,
        creditReward: sql`excluded.credit_reward`,
        xpReward: sql`excluded.xp_reward`,
        lootTable: sql`excluded.loot_table`,
        requiresFleet: sql`excluded.requires_fleet`,
        icon: sql`excluded.icon`,
        description: sql`excluded.description`,
      },
    })
  console.log(`  Inserted/updated ${allEntities.length} entities`)

  console.log("Combat seed complete.")
  process.exit(0)
}

main().catch((err) => {
  console.error("Seed failed:", err)
  process.exit(1)
})
